baseURL: 'https://event.ubuntu-kr.org'
languageCode: ko-kr
title: 'Ubuntu Korea Community Events'
theme: "ubuntukr"
buildFuture: true
googleAnalytics: "UA-65961752-7"
disqusShortname: ubuntu-kr-blog
paginate: 5
permalinks: 
  events: /:2006/:01/:02/:filename
outputs:
  section: ["HTML", "RSS", "Calendar"]
params:
  contact: contact@ubuntu-kr.org
  facebook: ubuntukorea
  twitter: UbuntuKrOrg
  github: ubuntu-kr
  launchpad: ubuntu-ko
  youtube: https://www.youtube.com/user/UbuntuKorea
  source_repo: https://github.com/ubuntu-kr/event.ubuntu-kr.org
  gmaps_embed_api_key: AIzaSyAlFGcj4Yqrvr2cvFh7-TSN1EfaO1OK53Y
  calendarOrganizer: "Ubuntu Korea Community"
  calendarUidSuffix: UbuntuKrEvents
defaultContentLanguage: ko
languages:
  ko:
    languageName: 한국어
    title: 우분투 한국 커뮤니티 행사
    weight: 1
    params:
      description: >-
        우분투 한국 커뮤니티의 각종 행사 일정을 알아보세요.
      copyright: >-
        © 2021 우분투 한국 커뮤니티 (우분투 한국 로컬 커뮤니티 팀).
        별도 고지가 있는 경우를 제외하고, 웹 사이트 소스코드는 MIT, 웹 사이트의 컨텐츠는 CC BY-SA 4.0 라이선스로 이용 가능합니다.
        Ubuntu 및 Canonical 은 Canonical Ltd. 의 등록 상표입니다.
      main_slide:
        label: 커뮤니티 소개
        link: about
    menu:
      main:
      - identifier: events
        name: 행사
        weight: 1
        url: /
      - identifier: calendar
        name: 일정 구독(ICS)
        weight: 2
        url: /events/index.ics
      link:
      - identifier: home
        name: 홈페이지
        weight: 1
        url: https://ubuntu-kr.org
      - identifier: forum
        name: 포럼
        weight: 2
        url: https://forum.ubuntu-kr.org
      - identifier: wiki
        name: 위키
        weight: 3
        url: https://wiki.ubuntu-kr.org
      - identifier: tutorials
        name: 튜토리얼
        weight: 4
        url: https://ubuntu-kr.github.io/workshops/
      - identifier: blog
        name: 블로그
        weight: 5
        url: https://blog.ubuntu-kr.org
      - identifier: ask
        name: Ask Ubuntu KR 
        weight: 6
        url: https://ask.ubuntu-kr.org
  en:
    languageName: English
    title: Ubuntu Korea Community Events
    weight: 2
    params:
      description: >-
        Find out various scheduled events of Ubuntu Korea Community
      copyright: >-
        © 2021 Ubuntu Korea Community (Ubuntu Korean LoCo Team).
        Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY-SA 4.0. 
        Ubuntu and Canonical are registered trademarks of Canonical Ltd.
      main_slide:
        label: About the community
        link: about
    menu:
      main:
      - identifier: events
        name: Events
        weight: 1
        url: /
      - identifier: calendar
        name: Subscribe(ICS)
        weight: 2
        url: /events/index.ics
      link:
      - identifier: home
        name: Homepage
        weight: 1
        url: https://ubuntu-kr.org
      - identifier: forum
        name: Forum
        weight: 2
        url: https://forum.ubuntu-kr.org
      - identifier: wiki
        name: Wiki
        weight: 3
        url: https://wiki.ubuntu-kr.org
      - identifier: tutorials
        name: Tutorials
        weight: 4
        url: https://ubuntu-kr.github.io/workshops/
      - identifier: blog
        name: Blog
        weight: 5
        url: https://blog.ubuntu-kr.org
      - identifier: ask
        name: Ask Ubuntu KR 
        weight: 6
        url: https://ask.ubuntu-kr.org
